/** المسارات فقط (بدون /api) لأن api instance له baseURL: '/api' */
const BASE = '';

export const endpoints = {
  auth: {
    register: () => BASE + '/auth/register',
    login: () => BASE + '/auth/login',
    completeProfile: () => BASE + '/auth/complete-profile',
    googleUrl: () => BASE + '/auth/google',
    refresh: () => BASE + '/auth/refresh',
    me: () => BASE + '/auth/me',
  },
  users: { profile: () => BASE + '/users/profile' },
  trips: {
    list: () => BASE + '/trips',
    byId: (id: string) => BASE + '/trips/' + id,
    create: () => BASE + '/trips',
    update: (id: string) => BASE + '/trips/' + id,
    delete: (id: string) => BASE + '/trips/' + id,
    addImage: (id: string) => BASE + '/trips/' + id + '/images',
    removeImage: (id: string, imageId: string) => BASE + '/trips/' + id + '/images/' + imageId,
    addFeature: (id: string) => BASE + '/trips/' + id + '/features',
    updateFeature: (id: string, featureId: string) => BASE + '/trips/' + id + '/features/' + featureId,
    removeFeature: (id: string, featureId: string) => BASE + '/trips/' + id + '/features/' + featureId,
    addItineraryDay: (id: string) => BASE + '/trips/' + id + '/itinerary',
    updateItineraryDay: (id: string, dayId: string) => BASE + '/trips/' + id + '/itinerary/' + dayId,
    removeItineraryDay: (id: string, dayId: string) => BASE + '/trips/' + id + '/itinerary/' + dayId,
    addMeal: (id: string) => BASE + '/trips/' + id + '/meals',
    updateMeal: (id: string, mealId: string) => BASE + '/trips/' + id + '/meals/' + mealId,
    removeMeal: (id: string, mealId: string) => BASE + '/trips/' + id + '/meals/' + mealId,
    addHotel: (id: string) => BASE + '/trips/' + id + '/hotels',
    updateHotel: (id: string, hotelId: string) => BASE + '/trips/' + id + '/hotels/' + hotelId,
    removeHotel: (id: string, hotelId: string) => BASE + '/trips/' + id + '/hotels/' + hotelId,
    addIncluded: (id: string) => BASE + '/trips/' + id + '/included',
    updateIncluded: (id: string, itemId: string) => BASE + '/trips/' + id + '/included/' + itemId,
    removeIncluded: (id: string, itemId: string) => BASE + '/trips/' + id + '/included/' + itemId,
    addExcluded: (id: string) => BASE + '/trips/' + id + '/excluded',
    updateExcluded: (id: string, itemId: string) => BASE + '/trips/' + id + '/excluded/' + itemId,
    removeExcluded: (id: string, itemId: string) => BASE + '/trips/' + id + '/excluded/' + itemId,
  },
  landmarks: {
    list: () => BASE + '/landmarks',
    byId: (id: string) => BASE + '/landmarks/' + id,
    create: () => BASE + '/landmarks',
    update: (id: string) => BASE + '/landmarks/' + id,
    delete: (id: string) => BASE + '/landmarks/' + id,
    addImage: (id: string) => BASE + '/landmarks/' + id + '/images',
    removeImage: (id: string, imageId: string) => BASE + '/landmarks/' + id + '/images/' + imageId,
  },
  cars: {
    list: () => BASE + '/cars',
    byId: (id: string) => BASE + '/cars/' + id,
    create: () => BASE + '/cars',
    update: (id: string) => BASE + '/cars/' + id,
    delete: (id: string) => BASE + '/cars/' + id,
    addImage: (id: string) => BASE + '/cars/' + id + '/images',
    removeImage: (id: string, imageId: string) => BASE + '/cars/' + id + '/images/' + imageId,
  },
  bookings: {
    createTrip: (tripId: string) => BASE + '/bookings/trips/' + tripId,
    createCar: (carId: string) => BASE + '/bookings/cars/' + carId,
    carPricePreview: (carId: string) => BASE + '/bookings/cars/' + carId + '/price-preview',
    uploadLicense: () => BASE + '/bookings/cars/upload-license',
    myTripBookings: () => BASE + '/bookings/trips/my',
    myCarBookings: () => BASE + '/bookings/cars/my',
    adminTripBookings: () => BASE + '/bookings/admin/trips',
    adminCarBookings: () => BASE + '/bookings/admin/cars',
  },
  reviews: {
    tripReviews: (tripId: string) => BASE + '/reviews/trips/' + tripId,
    carReviews: (carId: string) => BASE + '/reviews/cars/' + carId,
    createTripReview: (tripId: string) => BASE + '/reviews/trips/' + tripId,
    createCarReview: (carId: string) => BASE + '/reviews/cars/' + carId,
  },
  favorites: { list: () => BASE + '/favorites', add: () => BASE + '/favorites', remove: (id: string) => BASE + '/favorites/' + id },
  discounts: { list: () => BASE + '/discounts', byId: (id: string) => BASE + '/discounts/' + id, create: () => BASE + '/discounts', update: (id: string) => BASE + '/discounts/' + id, delete: (id: string) => BASE + '/discounts/' + id },
  coupons: { list: () => BASE + '/coupons', byId: (id: string) => BASE + '/coupons/' + id, byCode: (code: string) => BASE + '/coupons/code/' + code, create: () => BASE + '/coupons', update: (id: string) => BASE + '/coupons/' + id, delete: (id: string) => BASE + '/coupons/' + id },
  payments: {
    tripSession: (bookingId: string) => BASE + '/payments/trip-booking/' + bookingId + '/session',
    carSession: (bookingId: string) => BASE + '/payments/car-booking/' + bookingId + '/session',
  },
} as const;
